### ISSUE TITLE
Preview window for selected attachment types - priority is images, then video and audio. 

### ISSUE THREAD

**Issue by ManZzup** [ECLK/IncidentManagement#170]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When viewing attachments in the event trail, allow a pre-defined set of file types to be previewed in a pop-up window. Suggested images, videos, and pdf.

**Describe alternatives you've considered**
None

**Comment by nshamit** [comment]
Not only preview - allow them to view the file, hear the entire audio and view the entire video in pop up.

**Comment by nshamit** [comment]
**Comment from ICTA :**

**Describe the bug**
Complaint Coordinator should to be able to open up links, audio, video and images in a pop up rather than having to download the attachments but at the moment every attachment is getting downloaded.

**Expected behavior**
Complaint Coordinator should to be able to open up links, audio, video and images in a pop up rather than having to download the attachments

**Comment by nshamit** [comment]
priority:

1. images
2. video
3. audio

**Comment by ManZzup** [comment]
29/10/2019

**Comment by ManZzup** [comment]
Fixed
