### ISSUE TITLE
public user form fixes

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#333]
**Describe the bug**
- [x] mode is not set.
  - make '/channel' endpoint public
- [x] empty header does not signifies that it's form eC
  - update header with main page
- [x] remove held elections from the list.
  - if one election is left, may it be selected already.

**Comment by MrClemRkz** [comment]
completed.

**Comment by nshamit** [comment]
- [ ] 1. Include "*fields are mandatory" at the top of the from 

- [ ] 2. Remove "Cannot be changed after Submitting"

- [ ] 3. State "Select election". Remove the word corresponding

- [ ] 4. Change to "Describe the incident location"

- [ ] 5.  Change "Address of the incident location" to "Address"

- [ ] 6. Change to "City of the incident location" to "City"

- [ ] 7. Change Mobile to second line instead of third line.

**Comment by MrClemRkz** [comment]
completed.
